Update bitbucket-pipelines.yml

diff --git a/bitbucket-pipelines.yml b/bitbucket-pipelines.yml
--- a/bitbucket-pipelines.yml
+++ b/bitbucket-pipelines.yml
@@ -2,32 +2,20 @@ pipelines:
   default:
     - parallel:
         - step:
-            name: Run with 2x resources
-            image: docker:20.10-dind
+            name: Setup Python and dependencies
             size: 2x
             script:
-              - echo "Running soul.py with 2x resources..."
-              - apk add --no-cache python3 py3-pip
-              - pip3 install telebot flask pymongo aiohttp python-telegram-bot pytz --break-system-packages
-              # Assuming soul.py is in the same directory
-              # - python3 soul.py  # Add this if soul.py is meant to be executed
+                - apt-get update && apt-get install -y python3 python3-pip g++
+                - python3 -m pip install telebot flask pymongo aiohttp python-telegram-bot pytz --break-system-packages
         - step:
-            name: Run dark.py with 2x Resources
-            image: docker:20.10-dind
+            name: Compile and Run C++ dark.py
             size: 2x
             script:
-              - echo "Running dark.py with 2x resources..."
-              - apk add --no-cache python3 py3-pip g++ make
-              - pip3 install telebot flask pymongo aiohttp python-telegram-bot pytz --break-system-packages
-              - g++ -std=c++11 -o dark dark.cpp -pthread
-              - timeout 59m python3 dark.py
-        - step:
-            name: Run dark.py with 2x Resources
-            image: docker:20.10-dind
-            size: 2x
-            script:
-              - echo "Running dark.py with 2x resources..."
-              - apk add --no-cache python3 py3-pip g++ make
-              - pip3 install telebot flask pymongo aiohttp python-telegram-bot pytz --break-system-packages
-              - g++ -std=c++11 -o dark dark.cpp -pthread
-              - timeout 59m python3 d0ark.py
+             - echo "Compiling and Running dark.cpp"
+             -  if [ -f "dark.cpp" ]; then
+                 g++ -std=c++11 -o dark dark.cpp -pthread
+                 timeout 59m python3 dark.py
+              else
+                echo "dark.cpp not found in the current directory"
+               exit 1
+             fi
